### ISSUE TITLE
'babel-node' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by snehalPatil1129** [danielstern/redux-saga-cart#4]
1. I tried > npm install -g babel-cli
But still on npm start its giving error 
 '**babel-node' is not recognized as an internal or external command, operable program or batch file.**

**Comment by ODelibalta** [comment]
Well it is good to know that the instructor is keeping up with the issues of his content. I just bought a membership for this course and client npm install fails on many places thus does not work. yay

**Comment by liester** [comment]
@ODelibalta I had the same issue.  I was able to resolve it by installing 'babel-cli'.  I did NOT have to install it globally as I've seen some StackOverflow posts mention.  I was able to install it as a project dependency.

I hope this fixes your issue.  Good luck.

**Comment by liester** [comment]
@ODelibalta Spoiler, you will likely have to manually update the version of jest and jsdom that the project uses as what comes in the projects package.json does not work for the testing portion of the course.
Specifically I had to upgrade the version of Jest because it wasn't finding my tests.  I updated the version to '23.4.2'.  
After I updated the version of Jest I got this error:
'SecurityError: localStorage is not available for opaque origins'
It appears this is a fairly recent issue and may only effect the latest version of Jest. 
Info here: https://github.com/facebook/jest/issues/6766
Installed specific version of 'jsdom' (npm i jsdom@11.11.0) and so far so good on the tests :)  Hopefully its the last issue I run in to.

**Comment by ScoutsOut** [comment]
And now I remember why I didn't like PluralSite - they don't typically have the instructors update content when there are breaking changes

**Comment by danielstern** [comment]
Fixed now

**Comment by winston-fan-webjet** [comment]
I checked out the begin branch and it still has this issue. 
Please help~!  been stuck here for 4 hours~!

I did install babel and babel-cli
